typedef enum {
    CREDIT_CARD = 0,
    MPU = 1,
    UPOP ,
    ALIPAY,
    ONE_TWO_THREE,
    MASTER_PASS,
    APPLE_PAY,
    QWIK,
    LINE_PAY
} My2c2pPaymentChannel;

typedef enum {
    PAYMENT_OPTION_ALL,
    PAYMENT_OPTION_FULL,
    PAYMENT_OPTION_INSTALLMENT,
    PAYMENT_OPTION_CREDIT_CARD,
    PAYMENT_OPTION_CREDIT_CARD_INSTALLMENT,
    PAYMENT_OPTION_ONE_TWO_THREE,
    PAYMENT_OPTION_MPU,
    PAYMENT_OPTION_UPOP,
    PAYMENT_OPTION_ALIPAY,
} My2c2pPaymentOption;


